server:
  port: 8002
  servlet:
    context-path: /business
spring:
  application:
    name: business
  datasource:
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
    username: train_business
    password: 1213707943
    url: jdbc:mysql://******:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ******         # Redis服务器地址
      port: 6379              # Redis服务器连接端口
      password: 1213707943
      database: 0
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  level:
    com.train.mapper: debug
