server:
  port: 8003
  servlet:
    context-path: /batch
spring:
  application:
    name: batch
  datasource:
    username: train_batch
    password: 1213707943
    url: jdbc:mysql://******:3306/train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  level:
    com.train.mapper: debug
